name: Build and Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends libclang-dev

      - name: Set up Rust toolchain
        run: rustup component add rustfmt clippy

      - name: Version information
        run: rustc --version; cargo --version; rustup --version

      - name: Calculate Dependencies
        run: cargo generate-lockfile

      - name: Cache Rust dependencies
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: |
            ~/.cargo/registry
            target
          key: deps-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - name: Build all
        run: cargo build --all

      - name: Assert compiled tests were committed
        run: git diff --exit-code -- tests/

      - name: Run linting
        run: |
          set -eo pipefail
          cargo fmt -- --check
          cargo clippy

      - name: Run all tests
        run: |
          cargo test --all
          # also run tests with oniguruma
          cargo test --all --features oniguruma
